name: voice_tutor_app
description: "AI English Voice Tutor App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  record: ^5.1.2
  audioplayers: ^6.0.0
  http: ^1.2.1
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
